# Powtórka podstawowych rachunków wektorowych i macierzowych w Pythonie
## Działania na tablicach `numpy`
Do działań na wektorach i macierzach użyjemy modułu `numpy`. Zaimportujmy go:

In [3]:
import numpy as np

Natywnym typem zmiennych w `numpy` są tablice, czyli `array`.

Można je zadeklarować zarówno przez podanie listy własnych liczb, albo użyć metod generujących tablice z samymi zerami, jedynkami lub liczbami losowymi ze ustandardyzowanego rozkładu normalnego N(0,1).

In [4]:
v = np.array([1,2,3,4])
v0 = np.zeros(4) # (rozmiar)
v1 = np.ones(4)
vrand = np.random.randn(4)
print(v)
print(v0)
print(v1)
print(vrand)

[1 2 3 4]
[0. 0. 0. 0.]
[1. 1. 1. 1.]
[-0.75037378 -0.98890522 -0.13947768 -0.44968722]


Konkretny kształt (wymiarowość) możemy im nadać zarówno w momencie deklaracji, jak i po. Do sprawdzenia kształtu służy metoda `shape`, do zmiany kształtu - metoda `reshape`. Liczbę elementów można sprawdzić metodą `size` lub funkcją `len`.

In [5]:
x = np.array([[1,2],[3,4]])
x0 = np.zeros((2,2))
print(x)
print(x0)

[[1 2]
 [3 4]]
[[0. 0.]
 [0. 0.]]


In [6]:
vr = v.reshape(4,1)
print('Przed zmianą: wektor wierszowy')
print(v)
print('Kształt', v.shape)
print('Liczba elementów: ', v.size, 'albo', len(v))
print('Po zmianie: wektor kolumnowy')
print(vr)
print('Kształt', vr.shape)
print('Liczba elementów: ', vr.size, 'albo', len(vr))

Przed zmianą: wektor wierszowy
[1 2 3 4]
Kształt (4,)
Liczba elementów:  4 albo 4
Po zmianie: wektor kolumnowy
[[1]
 [2]
 [3]
 [4]]
Kształt (4, 1)
Liczba elementów:  4 albo 4


Transpozycja macierzy w `numpy` jest fantastycznie prosta (jak wszystko w Pythonie): transponowana_tablica = tablica.T

Proszę sprawdzić porównać kształty tablic 1D wierszowej i kolumnowej, czyli np. zadeklarowanych już v i vr z ich transpozycjami. 

In [28]:
print(v)
print(v.shape)

print(v.T)
print((v.T).shape)

print(vr)
print(vr.shape)

print(vr.T)
print((vr.T).shape)


[1 2 3 4]
(4,)
[1 2 3 4]
(4,)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[[1 2 3 4]]
(1, 4)


Proszę sprawdzić kształt i transpozycję macierzy 2x2, np. 
$A =
\left[
\begin{array}{cc}
1 & 2 \\
3 & 4
\end{array}
\right]
$

In [20]:
A = np.array([[1,2],[3,4]])
print(A.shape)
print(A.T)
print((A.T).shape)

(2, 2)
[[1 3]
 [2 4]]
(2, 2)


Operator `*` służy do mnożenia dwóch macierzy element po elemencie, do mnożenia elementów wektora przez elementy rzędów macierzy, albo do mnożenia macierzy przez skalar:

In [21]:
print(A*A)

[[ 1  4]
 [ 9 16]]


In [22]:
print(2*A)

[[2 4]
 [6 8]]


In [23]:
vec = np.array([1,2])
print(vec*A)

[[1 4]
 [3 8]]


Do mnożenia macierzy i macierzy i wektorów służy funkcja `np.dot`:

In [24]:
print(np.dot(A,A)) 
print(np.dot(vec,A))
print(np.dot(A,vec))

[[ 7 10]
 [15 22]]
[ 7 10]
[ 5 11]


Przeanalizuj, co robią następujące polecenia:

In [25]:
x = np.array([1,2,3,4]).reshape(4,1)
print(x)
#zmiana macierzy wierszowej na kolumnową

[[1]
 [2]
 [3]
 [4]]


In [26]:
print(np.dot(x.T,x))
# mnoży wektor wierszowy z komunowym (jego transpozycją) -> iloczyn skalarny wektora ze sobą (kwadrat normy)

[[30]]


In [27]:
print(np.dot(x,x.T))

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [ ]:
#mnoży wektor kolumnowy z wierszowym (jego transpozycją)-> mamy macierz